#!/usr/bin/env python3
"""Regenerate src/lib/reading-log.ts from a Douban CSV export.

Usage: python3 scripts/update-reading-log.py [path-to-douban-export.csv]
"""
import csv, json, pathlib

import sys
base = pathlib.Path(__file__).resolve().parent.parent
src = sys.argv[1] if len(sys.argv) > 1 else str(base / 'booklist-douban.csv')
out = str(base / 'src' / 'lib' / 'reading-log.ts')

rows = []
with open(src, encoding='utf-8-sig') as f:
    for r in csv.DictReader(f):
        rows.append(r)

def clean_date(s):
    s = (s or '').strip()
    parts = s.split()
    if not parts:
        return ''
    d = parts[0]
    try:
        y, mo, dd = d.split('/')
        return f"{y}-{int(mo):02d}-{int(dd):02d}"
    except ValueError:
        return ''

books = []
for r in rows:
    title = (r.get('标题') or '').strip()
    if not title:
        continue
    rating_raw = (r.get('个人评分') or '').strip()
    rating = None
    try:
        rating = int(float(rating_raw))
    except (ValueError, TypeError):
        pass
    books.append({
        'title': title,
        'author': (r.get('作者') or '').strip(),
        'rating': rating,
        'dateRead': clean_date(r.get('打分日期')),
        'note': (r.get('我的短评') or '').strip(),
        'published': (r.get('出版日期') or '').strip(),
        'url': (r.get('条目链接') or '').strip(),
    })

books.sort(key=lambda b: (b['dateRead'] == '', b['dateRead'] or ''), reverse=True)

rated = [b for b in books if b['rating'] is not None]
avg = round(sum(b['rating'] for b in rated) / len(rated), 2) if rated else 0

lines = []
lines.append("// Reading log exported from Douban on 2026-08-11.")
lines.append("// Generated by script — do not edit by hand.")
lines.append("")
lines.append("export interface ReadingLogEntry {")
lines.append("  title: string;")
lines.append("  author: string;")
lines.append("  rating: number | null;")
lines.append("  dateRead: string; // YYYY-MM-DD, '' when unknown")
lines.append("  note?: string;")
lines.append("  published: string;")
lines.append("  url: string;")
lines.append("}")
lines.append("")
lines.append("export const readingLog: ReadingLogEntry[] = [")
for b in books:
    note = b['note'].replace('\\', '\\\\').replace('"', '\\"').replace('\n', ' ')
    lines.append("  {")
    lines.append(f"    title: {json.dumps(b['title'], ensure_ascii=False)},")
    lines.append(f"    author: {json.dumps(b['author'], ensure_ascii=False)},")
    lines.append(f"    rating: {b['rating'] if b['rating'] is not None else 'null'},")
    lines.append(f"    dateRead: {json.dumps(b['dateRead'])},")
    if note:
        lines.append(f"    note: {json.dumps(note, ensure_ascii=False)},")
    lines.append(f"    published: {json.dumps(b['published'], ensure_ascii=False)},")
    lines.append(f"    url: {json.dumps(b['url'])},")
    lines.append("  },")
lines.append("];")
lines.append("")
lines.append("export const readingLogStats = {")
lines.append(f"  total: {len(books)},")
lines.append(f"  rated: {len(rated)},")
lines.append(f"  averageRating: {avg},")
lines.append("  distribution: {")
lines.append("    5: %d, 4: %d, 3: %d, 2: %d, 1: %d," % (
    sum(1 for b in books if b['rating'] == 5),
    sum(1 for b in books if b['rating'] == 4),
    sum(1 for b in books if b['rating'] == 3),
    sum(1 for b in books if b['rating'] == 2),
    sum(1 for b in books if b['rating'] == 1),
))
lines.append("  },")
lines.append("};")
lines.append("")

with open(out, 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines))

print(f"OK: {len(books)} books -> {out}")
print(f"rated={len(rated)} avg={avg} dist={{5:%d,4:%d,3:%d,2:%d,1:%d}}" % (
    sum(1 for b in books if b['rating'] == 5),
    sum(1 for b in books if b['rating'] == 4),
    sum(1 for b in books if b['rating'] == 3),
    sum(1 for b in books if b['rating'] == 2),
    sum(1 for b in books if b['rating'] == 1),
))
